# Site settings
title: Fox Blog
header-img: img/home-bg.jpg
email: foxplusplus@gmail.com
description: "fox blog"
baseurl: ""
url: "http://yourdomain.com"
#twitter_username: SBootstrap
github_username:  foxpp
#facebook_username:  IronSummitMedia

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
gems: [jekyll-paginate]
